// =======================================================================================
// This Sail RISC-V architecture model, comprising all files and
// directories except where otherwise noted is subject the BSD
// two-clause license in the LICENSE file.
//
// SPDX-License-Identifier: BSD-2-Clause
// =======================================================================================

enum zvabd_vabd_func6 = {VABD, VABDU}
enum zvabd_vwabda_func6 = {VWABDA, VWABDAU}
