// =======================================================================================
// This Sail RISC-V architecture model, comprising all files and
// directories except where otherwise noted is subject the BSD
// two-clause license in the LICENSE file.
//
// SPDX-License-Identifier: BSD-2-Clause
// =======================================================================================

enum vabdop = {VABS_V, VABD_VV, VABDU_VV, VWABDACC_VV, VWABDACCU_VV} 