chapter \<open>Generated by Lem from \<open>function_extra.lem\<close>.\<close>

theory "Lem_function_extra" 

imports
  Main
  "Lem_maybe"
  "Lem_bool"
  "Lem_basic_classes"
  "Lem_num"
  "Lem_function"
  "Lem"

begin 



\<comment> \<open>\<open>open import Maybe Bool Basic_classes Num Function\<close>\<close>

\<comment> \<open>\<open>open import {hol} `lemTheory`\<close>\<close>
\<comment> \<open>\<open>open import {isabelle} `$LIB_DIR/Lem`\<close>\<close>

\<comment> \<open>\<open> ----------------------- \<close>\<close>
\<comment> \<open>\<open> getting a unique value  \<close>\<close>
\<comment> \<open>\<open> ----------------------- \<close>\<close>

\<comment> \<open>\<open>val THE : forall 'a. ('a -> bool) -> maybe 'a\<close>\<close>

end
