set(default_config_filename "${CMAKE_INSTALL_DATADIR}/${CMAKE_PROJECT_NAME}/config")
set(config_schema "${CMAKE_BINARY_DIR}/sail_riscv_config_schema.json")
file(READ ${default_config_filename} DEFAULT_JSON)
file(READ ${config_schema} JSON_SCHEMA)
configure_file("default_config.h.in" "default_config.h" @ONLY)
