#pragma once

// The header generated by Sail.
#include RISCV_MODEL_HEADER

#ifdef __cplusplus
extern "C" {
#endif

// The generated header does not include these functions.
void model_init(void);
void model_fini(void);

// The generated header does not include these variables.
// TODO: We should avoid accessing variables directly.
extern mach_bits zxlen;
extern mach_bits zflen;
extern mach_bits zphysaddrbits_len;
extern mach_bits zVLEN;

#ifdef __cplusplus
}
#endif
