#pragma once

// The header generated by Sail.
#include "sail_riscv_model.h"

#ifdef __cplusplus
extern "C" {
#endif

// The generated header does not include these functions.
void model_init(void);
void model_fini(void);

// The generated header does not include these variables.
// TODO: We should avoid accessing variables directly.
extern uint64_t zxlen;
extern uint64_t zflen;
extern uint64_t zphysaddrbits_len;

#ifdef __cplusplus
}
#endif
