#pragma once

// The header generated by Sail.
#include RISCV_MODEL_HEADER

#ifdef __cplusplus
extern "C" {
#endif

// The generated header does not include these functions.
void model_init();
void model_fini();

extern mach_bits zxlen_val;

#ifdef __cplusplus
}
#endif
