# vim: set tabstop=4 shiftwidth=4 noexpandtab
# ====================================================================================================================
# Filename:		Makefile.common
#
# Description:	Makefile for building and running 
#
# Author(s):	Bill McSpadden (bill@riscv.org)
#
# Revision:		See git log
#
# ====================================================================================================================

# SHELL is set to /bin/sh as default for make
#	On Ubuntu,  /bin/sh is a symlink to /bin/dash
#	/bin/dash does not behave much like bash.
#	I want bash to be the shell we use in this environment,
#	not dash.
SHELL := /bin/bash
$(info SHELL: ${SHELL})

# TEST_DIR_PATH_KEYDIR is the directory name under which the
#	test directory exists.  This directory contains the items
#	needed to build and run RISC-V tests.  This keyword is needed
#	in order that this makefile and all 'included' makefiles can
#	find the consistent set of tools for building and running
#	tests.
ifndef TEST_DIR_PATH_KEYDIR
$(error The make variable \'TEST_DIR_PATH_KEYDIR\' must be set.)
endif

# TODO: need to consider how to support both LLVM and gcc.
ifndef RISCV32_TOOL_PATH
$(error The environment variable, \'RISCV32_TOOL_PATH\' must be set)
endif

ifndef RISCV64_TOOL_PATH
$(error The environment variable, \'RISCV64_TOOL_PATH\' must be set)
endif


$(info TEST_DIR_PATH: ${TEST_DIR_PATH})
$(info TEST_DIR_PATH realpath: $(realpath ${TEST_DIR_PATH}))
$(info TEST_DIR_PATH abspath:  $(abspath ${TEST_DIR_PATH}))

TESTDIRS 		:= $(wildcard *.testdir)


CC				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-gcc
ASM				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-gcc
LD 				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-ld



all:


build:
	@echo "making \"$@\" in $$PWD" ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		echo "calling \'make $@\'" ;									\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		done;
	if [ ! -z "${TESTLIST_BUILD}" ] ;															\
		then																		\
		echo "calling \'make build_tests\'" ;										\
		make build_tests ;															\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make build_tests' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		fi;


build_tests : ${TESTLIST_BUILD}
#${TESTLIST_BUILD} :
#	@echo "making \"$@\" in $$PWD" ;
#	@mkdir -p $@.artifactdir || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
#	@echo "calling \'make $@\'" ;
#	make $@ ;														\
#	if [ $$? -ne 0 ] ;                                              								\
#		then                                                            							\
#		echo "\'make $@\' exited with nonzero exit status" >> $@.artifactdir/test.failed ;						\
#		fi ;

#$(call get,OBJDIR_AA,${UNIQ_TESTNAME})/%.o : %.s %.S
$(call get,OBJDIR_AA,${UNIQ_TESTNAME})/%.o :  %.S
	@echo "making \"$@\" in $$PWD" ;
	@mkdir -p $(call get,OBJDIR_AA,${UNIQ_TESTNAME}) || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
	${ASM} -c $(call get,ASM_FLAGS_AA,${UNIQ_TESTNAME}) 	\
		-o $@ 												\
		$(call get,ASM_SRC_AA,${UNIQ_TESTNAME})


$(call get,OBJDIR_AA,${UNIQ_TESTNAME})/test.elf : $(call get,OBJS_AA,${UNIQ_TESTNAME})
	@echo "making \"$@\" in $$PWD" ;
	${LD} $(call get,LD_FLAGS_AA,${UNIQ_TESTNAME}) -o $@ $<


install:

run:
	@echo "making \"$@\" in $$PWD" ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		done;
	if [ ! -z "${TESTLIST}" ] ;															\
		then																		\
		make run_tests ;															\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make run_tests' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		fi;


# Run in parallel (potentially,  based on the -j switch to make)
#	TODO: also redirect stderr into test.failed
.PHONY: ${TESTLIST}
run_tests : ${TESTLIST}
${TESTLIST} :
	@echo "making \"$@\"" ;
	@mkdir -p $@.artifactdir || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
	@if [ ! -e ${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$(call get,XLEN_AA,$@) ] ; 									\
		then																						\
		echo "${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$(call get,XLEN_AA,$@) does not exist." >> $@.artifactdir/test.failed ;	\
		fi ;
	${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$(call get,XLEN_AA,$@) $(call get,RUN_FLAGS_AA,$@) $(call get,OBJDIR_AA,${UNIQ_TESTNAME})/test.elf > $@.artifactdir/test.run.stdout	; 					\
	if [ $$? -ne 0 ] ;                                              								\
		then                                                            							\
		echo "riscv_sim_$@.$(call get,XLEN_AA,$@) exited with nonzero exit status" >> $@.artifactdir/test.failed ;						\
		fi ;
	@if [ ! -e $@.artifactdir/test.run.stdout ] ;																\
		then																						\
		echo "file, \"$@.artifactdir/test.run.stdout\" not found" >> $@.artifactdir/test.failed ;										\
		fi ;
	@if [ ! -e $@.artifactdir/test.failed ] ;																	\
		then																						\
		echo "${PWD} passed" >> $@.artifactdir/test.passed ;													\
		fi;


# Gather all the test results from this directory  on down.
#	Do not run this target in parallel,  else the output into
#	./test.failed will get intermixed and become unreadable.
check :
	@echo "$$PWD: making \"$@\"" ;
	@rm -f test.passed test.failed ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		if [ -e $$testdir/test.failed ] ;										\
			then																\
			echo "ERROR: test.failed exists in $$testdir." >> test.failed;		\
			cat $$testdir/test.failed >> test.failed ;							\
			fi ;																\
		if [ ! -e ./test.failed ] ;												\
			then																\
			if [ -e $$testdir/test.passed ] ;									\
				then															\
				echo "test.passed exists in $$testdir" >> test.passed ;			\
				cat $$testdir/test.passed >> test.passed ;						\
				fi ;															\
			fi;																	\
		done;
	@for artifactdir in ${ARTIFACTDIRS}; 										\
		do																		\
		if [ -e $$artifactdir/test.failed ] ;									\
			then																\
			echo "$$artifactdir/test.failed exists." >> test.failed;			\
			cat $$artifactdir/test.failed >> test.failed ;						\
			fi;																	\
		if [ -e $$artifactdir/test.passed ] ;									\
			then																\
			echo "$$PWD/$$artifactdir/test.passed exists." >> test.passed;			\
			fi;																	\
		if [ ! -e $$artifactdir/test.failed ] ;									\
			then																\
			if [ ! -e $$artifactdir/test.passed ] ;								\
				then															\
				echo "neither $$PWD/$$artifactdir/test.failed nor test.passed exists." >> test.failed ; 	\
				fi ;																				\
			fi;																						\
		done ;
	
	

clean:
	rm -f test.failed test.passed
	rm -rf *.artifactdir

# Cleans local artifacts and the install location
clean_all:



