# vim: set tabstop=4 shiftwidth=4 noexpandtab
# ====================================================================================================================
# Filename:		Makefile.common
#
# Description:	Makefile for building and running 
#
# Author(s):	Bill McSpadden (bill@riscv.org)
#
# Revision:		See git log
#
# ====================================================================================================================

# SHELL is set to /bin/sh as default for make
#	On Ubuntu,  /bin/sh is a symlink to /bin/dash
#	/bin/dash does not behave much like bash.
#	I want bash to be the shell we use in this environment,
#	not dash.
SHELL := /bin/bash
$(info SHELL: ${SHELL})

# TEST_DIR_PATH_KEYDIR is the directory name under which the
#	test directory exists.  This directory contains the items
#	needed to build and run RISC-V tests.  This keyword is needed
#	in order that this makefile and all 'included' makefiles can
#	find the consistent set of tools for building and running
#	tests.
ifndef TEST_DIR_PATH_KEYDIR
$(error The make variable \'TEST_DIR_PATH_KEYDIR\' must be set.)
endif

# TODO:  how to check for availablity of toolsuite
## TODO: need to consider how to support both LLVM and gcc.
#ifndef RISCV32_TOOL_PATH
#$(error The environment variable, \'RISCV32_TOOL_PATH\' must be set)
#endif
#
#ifndef RISCV64_TOOL_PATH
#$(error The environment variable, \'RISCV64_TOOL_PATH\' must be set)
#endif


$(info TEST_DIR_PATH: ${TEST_DIR_PATH})
$(info TEST_DIR_PATH realpath: $(realpath ${TEST_DIR_PATH}))
$(info TEST_DIR_PATH abspath:  $(abspath ${TEST_DIR_PATH}))
$(info UNIQ_TESTNAME: ${UNIQ_TESTNAME})

TESTDIRS 		:= $(wildcard *.testdir)


#CC				:= riscv32-unknown-elf-gcc
#ASM				:= riscv32-unknown-elf-gcc
#LD 				:= riscv32-unknown-elf-ld

#CC				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-gcc
#ASM				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-gcc
#LD 				:= ${RISCV32_TOOL_PATH}/riscv32-unknown-elf-ld

#CC				:= ${RISCV64_TOOL_PATH}/riscv64-unknown-elf-gcc
#ASM				:= ${RISCV64_TOOL_PATH}/riscv64-unknown-elf-gcc
#LD 				:= ${RISCV64_TOOL_PATH}/riscv64-unknown-elf-ld



all:


build:
	@echo "making \"$@\" in $$PWD" ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		echo "calling \'make $@\'" ;									\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		done;
	if [ ! -z "${TESTLIST_BUILD}" ] ;															\
		then																		\
		echo "calling \'make build_tests\'" ;										\
		make build_tests ;															\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make build_tests' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		fi;

# Convert gmsl assoc arrays into text suitable for bash assoc arrays
ASM_FLAGS_AA_FOR_SH := $(foreach var,${TESTLIST},["$(var)"]="$(call get,ASM_FLAGS_AA,$(var))" )
CC_FLAGS_AA_FOR_SH 	:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,CC_FLAGS_AA,$(var))" )
LD_FLAGS_AA_FOR_SH 	:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,LD_FLAGS_AA,$(var))" )
RUN_FLAGS_AA_FOR_SH := $(foreach var,${TESTLIST},["$(var)"]="$(call get,RUN_FLAGS_AA,$(var))" )
XLEN_AA_FOR_SH 		:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,XLEN_AA,$(var))" )
ASM_AA_FOR_SH 		:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,ASM_AA,$(var))" )
CC_AA_FOR_SH 		:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,CC_AA,$(var))" )
LD_AA_FOR_SH 		:= $(foreach var,${TESTLIST},["$(var)"]="$(call get,LD_AA,$(var))" )

$(info ASM_FLAGS_AA_FOR_SH: ${ASM_FLAGS_AA_FOR_SH})



test :
	arr=(${OBJDIRS_SET}) ; \
	echo "arr[]: $${arr[@]}";
	testlist=(${TESTLIST}) ; \
	echo "testlist[]: $${testlist[@]}";
	declare -A asm_flags_aa=( ${ASM_FLAGS_AA_FOR_SH} ) ; 	\
	echo "asm_flags_aa[]: $${asm_flags_aa[@]}";
	declare -A cc_flags_aa=( ${CC_FLAGS_AA_FOR_SH} ) ; 		\
	echo "cc_flags_aa[]: $${cc_flags_aa[@]}";
	declare -A ld_flags_aa=( ${LD_FLAGS_AA_FOR_SH} ) ; 		\
	echo "ld_flags_aa[]: $${ld_flags_aa[@]}";
	declare -A run_flags_aa=( ${RUN_FLAGS_AA_FOR_SH} ) ; 	\
	echo "run_flags_aa[]: $${runflags_aa[@]}";
	declare -A xlen_aa=( ${XLEN_AA_FOR_SH} ) ; 				\
	echo "xlen_aa[]: $${xlen_aa[@]}";

.PHONY : ${TESTLIST}
build_tests : ${TESTLIST}
${TESTLIST} :
	@echo "making \"$@\" in $$PWD" ;
	mkdir -p $@.artifactdir || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
	declare -A cc_aa=( ${CC_AA_FOR_SH} ) ; 	\
	declare -A asm_aa=( ${ASM_AA_FOR_SH} ) ; 	\
	declare -A ld_aa=( ${LD_AA_FOR_SH} ) ; 	\
	declare -A asm_flags_aa=( ${ASM_FLAGS_AA_FOR_SH} ) ; 	\
	declare -A cc_flags_aa=( ${CC_FLAGS_AA_FOR_SH} ) ; 	\
	declare -A ld_flags_aa=( ${LD_FLAGS_AA_FOR_SH} ) ; 	\
	declare -A run_flags_aa=( ${RUN_FLAGS_AA_FOR_SH} ) ; 	\
	echo "calling \'make $@\'" ; \
	echo "make $@.artifactdir/test.elf ASM_FLAGS_NEXT=$${asm_flags_aa["$@"]} CC_FLAGS_NEXT=$${cc_flags_aa["$@"]} LD_FLAGS_NEXT=$${ld_flags_aa["$@"]}" ;		\
	make $@.artifactdir/test.elf \
		ASM_NEXT="$${asm_aa[$@]}" \
		ASM_FLAGS_NEXT="$${asm_flags_aa[$@]}" \
		CC_NEXT="$${cc_aa[$@]}" \
		CC_FLAGS_NEXT="$${cc_flags_aa[$@]}" \
		LD_NEXT="$${ld_aa[$@]}" \
		LD_FLAGS_NEXT="$${ld_flags_aa[$@]}" ;		\
	if [ $$? -ne 0 ] ;                                              								\
		then                                                            							\
		echo "\'make $@\' exited with nonzero exit status" >> $@.artifactdir/test.failed ;						\
		fi ;

$(info foo: $(call get,OBJS_AA,${UNIQ_TESTNAME}))
$(info goo: $(call get,OBJDIR_AA,${UNIQ_TESTNAME}))
$(info OBJDIRS_SET: ${OBJDIRS_SET})
OBJDIRS_OBJS	:= $(addsuffix /%.o,${OBJDIRS_SET})
$(info OBJDIRS_OBJS: ${OBJDIRS_OBJS})

#$(call get,OBJDIR_AA,${UNIQ_TESTNAME})/%.o :  %.S
${OBJDIRS_OBJS} :  %.S
	@echo "making \"$@\" in $$PWD" ;
	@echo "ASM_FLAGS_NEXT: ${ASM_FLAGS_NEXT}" ;
	@mkdir -p $(dir $@) || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
	${ASM_NEXT} -c ${ASM_FLAGS_NEXT} -o $@ $<

${OBJDIRS_OBJS} :  %.c
	@echo "making \"$@\" in $$PWD" ;
	@mkdir -p $(dir $@) || ( echo "unable to create $@.artifactdir" >> test.failed ; exit $$? ; ) ;
	${CC_NEXT} -c ${CC_FLAGS_NEXT} -o $@ $<


OBJS	:= $(addprefix %/,${OBJS_BASE})
%/test.elf : ${OBJS}
	@echo "making \"$@\" in $$PWD" ;
	${LD_NEXT} ${LD_FLAGS_NEXT} -o $@ $<


install:

run:
	@echo "making \"$@\" in $$PWD" ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		done;
	if [ ! -z "${TESTLIST}" ] ;															\
		then																		\
		make run_tests ;															\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make run_tests' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		fi;


# TODO: Run in parallel (potentially,  based on the -j switch to make)
# TODO: also redirect stderr into test.failed
.PHONY: run_tests
run_tests :
	@echo "making \"$@\"" ;
	declare -A xlen_aa=( ${XLEN_AA_FOR_SH} ) ; 	\
	declare -A run_flags_aa=( ${RUN_FLAGS_AA_FOR_SH} ) ; 	\
	for testdir in ${TESTLIST} ; \
		do \
		mkdir -p $$testdir.artifactdir || ( echo "unable to create $$testdir.artifactdir" >> test.failed ; exit $$? ; ) ; \
		if [ ! -e ${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$${xlen_aa[$$testdir]} ] ; 									\
			then																						\
			echo "${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$${xlen_aa[$$testdir]} does not exist." >> $$testdir.artifactdir/test.failed ;	\
			fi ; \
		${TEST_DIR_PATH}/../../c_emulator/riscv_sim_RV$${xlen_aa[$$testdir]} $${run_flags_aa[$$testdir]} $$testdir.artifactdir/test.elf > $$testdir.artifactdir/test.run.stdout	; 					\
		if [ $$? -ne 0 ] ;                                              								\
			then                                                            							\
			echo "riscv_sim_RV$${xlen_aa[$$testdir]} exited with nonzero exit status" >> $$testdir.artifactdir/test.failed ;						\
			fi ; \
		if [ ! -e $$testdir.artifactdir/test.run.stdout ] ;																\
			then																						\
			echo "file, \"$$testdir.artifactdir/test.run.stdout\" not found" >> $$testdir.artifactdir/test.failed ;										\
			fi ; \
		if [ ! -e $$testdir.artifactdir/test.failed ] ;																	\
			then																						\
			echo "${PWD} passed" >> $$testdir.artifactdir/test.passed ;													\
			fi; \
		done ;


# Gather all the test results from this directory  on down.
#	Do not run this target in parallel,  else the output into
#	./test.failed will get intermixed and become unreadable.
check :
	@echo "$$PWD: making \"$@\"" ;
	@rm -f test.passed test.failed ;
	@for testdir in ${TESTDIRS}; 										\
		do																\
		if [ ! -e $$testdir/Makefile ] ;								\
			then														\
			echo "ERROR: no Makefile in $$testdir." >> test.failed;		\
			fi ;														\
		make -C $$testdir $@ ;											\
		if [ $$? -ne 0 ] ;                                              			\
			then                                                            		\
			echo "'make -C $$testdir $@' exited with nonzero exit status" >> test.failed ;	\
			fi ;																			\
		if [ -e $$testdir/test.failed ] ;										\
			then																\
			echo "ERROR: test.failed exists in $$testdir." >> test.failed;		\
			cat $$testdir/test.failed >> test.failed ;							\
			fi ;																\
		if [ ! -e ./test.failed ] ;												\
			then																\
			if [ -e $$testdir/test.passed ] ;									\
				then															\
				echo "test.passed exists in $$testdir" >> test.passed ;			\
				cat $$testdir/test.passed >> test.passed ;						\
				fi ;															\
			fi;																	\
		done;
	@for artifactdir in ${ARTIFACTDIRS}; 										\
		do																		\
		if [ -e $$artifactdir/test.failed ] ;									\
			then																\
			echo "$$artifactdir/test.failed exists." >> test.failed;			\
			cat $$artifactdir/test.failed >> test.failed ;						\
			fi;																	\
		if [ -e $$artifactdir/test.passed ] ;									\
			then																\
			echo "$$PWD/$$artifactdir/test.passed exists." >> test.passed;			\
			fi;																	\
		if [ ! -e $$artifactdir/test.failed ] ;									\
			then																\
			if [ ! -e $$artifactdir/test.passed ] ;								\
				then															\
				echo "neither $$PWD/$$artifactdir/test.failed nor test.passed exists." >> test.failed ; 	\
				fi ;																				\
			fi;																						\
		done ;
	
	

clean:
	rm -f test.failed test.passed
	rm -rf *.artifactdir

# Cleans local artifacts and the install location
clean_all:



