#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

help() {
    echo "Location: $0"
    script_name=$(basename "$0")
    echo "Usage: $script_name source-dir [dest-dir config]"
    echo "This script creates a histogram of instruction mnemonics from simulation traces"
    echo "of all the tests in the source-dir"
    echo "in the <dest-dir> directory"
    echo "by simulating it on the given <config> of the Sail RISC-V model"
    echo
    echo "Arguments:"
    echo "1: source-dir - the directory containing the tests to simulate (e.g., sail-riscv-tests/riscv-vector-tests-v128x64)"
    echo "2: dest-dir (optional, default: histograms)"
    echo "3: config (optional, default: /opt/sail-riscv/share/sail-riscv/config/rv64d_v128_e64.json)"
    exit 1
}

# Check if the first argument is provided
if [ -z "$1" ]; then
    help
fi


# The second argument is the destination directory for the histogram,
# optional, default is "histograms"
if [ -z "$2" ]; then
    dest_dir="histograms"
else
    dest_dir=$2
fi


# The third argument is the config file for the Sail RISC-V model,
# optional, default is "/opt/sail-riscv/share/sail-riscv/config/rv64d_v128_e64.json"
if [ -z "$3" ]; then
    config="/opt/sail-riscv/share/sail-riscv/config/rv64d_v128_e64.json"
else
    config=$3
fi


# Finally, create histograms for all tests in the source directory
tests=`find $1 -type f -executable`

for test in $tests
    do (sail-mnemonic-histogram "$test" "$dest_dir" "$config" &)
    done
