name: Build and Publish Base Container Image for SAIL

on:
  push:
    branches: [main]
    paths:
      - 'container/Dockerfile'

jobs:
  build-and-push-docker-image:
    name: Build and Push to RISC-V Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=now::$(date +'%m%d%Y')"

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            riscvintl/riscv-sail-toolchain-base-image:${{ github.sha }}
            riscvintl/riscv-sail-toolchain-base-image:latest
          push: ${{ github.event_name == 'push' }}
