name: Pre-commit Check

on: [push, pull_request, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: python3 -m pip install pre-commit

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Ensure pre-commit checks pass
        run: pre-commit run --all-files --show-diff-on-failure --color=always
