name: Run risc-v tests
on:
  workflow_dispatch:

jobs:
  download-riscv-tests:
    env:
      SAIL_VERSION: "0.19"
      CMAKE_VERSION: "3.20"

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install packages (Linux)
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends pkg-config libgmp-dev curl ninja-build jq

      - name: Download latest release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "nadime15/riscv-test-generator"
          latest: true
          fileName: "*.parta*"
          out-file-path: "download"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "${{ env.CMAKE_VERSION }}"

      - name: Combine downloaded chunks
        run: |
          cat download/*.parta* > download/riscv-tests.tar.gz
          ls download/

          tar -xzf download/riscv-tests.tar.gz -C test/
          rm download/*.part*

      - name: Install Sail (Linux)
        run: |
          sudo mkdir -p /usr/local
          curl --location https://github.com/rems-project/sail/releases/download/$SAIL_VERSION-linux-binary/sail.tar.gz | sudo tar xvz --directory=/usr/local --strip-components=1

          ./build_simulators.sh
          ctest --test-dir build --output-junit tests.xml --output-on-failure
